### PR TITLE
feat: SYS_ELEC Page upgrade to dynamic

### PR DESCRIPTION
**Pull request by tall-vish**
# Title
feat: SYS_ELEC Page upgrade to dynamic

# Description 
Changed the ELEC page in SYS from a static "image" to a dynamic page:
1) Recreated the entire display from scratch
2) All objects react to flow of electricity as expected
3) Apu bat is the same as Main Bat (temporary fix)
4) Load shed is non functional due to sim limitations
5) Engine Drive boxes are linked to generator boxes (drive disconnect button doesn't work)
6) Boxes in AC Bus are static (sim limitations)
7) Since no damage is simulated, the page will not react to failed systems

# Source material
787-fcom
Pages/chapter 6.10.5 to 6.10.13

[Pages.zip](https://github.com/Heavy-Division/B78XH/files/8962101/Pages.zip)

# Testing Instructions 
Run systems as expected, electric flow/generation lines should light up

# Test Results
flow lines/generation boxes light up as expected

[Pages.zip](https://github.com/Heavy-Division/B78XH/files/8962101/Pages.zip)
https://1drv.ms/v/s!Aud15_QCoWFBuPU8_q0l9v9LXm2mhA?e=lX1fLO

# Discord Username
vish#3861

### CODE REVIEW

**Review by kimlada — CHANGES_REQUESTED** [review]
Please do not use STRINGs for INTs and vice versa

**Comment by nakajimayoshi** [comment]
Screen Shot 2022-06-22 at 6 58 19 PM
It looks like you still have some git merge conflicts that need to be resolved? 

check the SYS.html and SYS.js files for lines containing "=====" or ">>>>>Stashed changes/ <<<<<< updated upstream" 

See [this Stackoverflow post](https://stackoverflow.com/questions/55366930/when-i-use-git-stash-i-end-up-with-updated-upstream-and-other-things-in) for info on stashing changes

**Comment by nakajimayoshi** [comment]
Trainee Report
Discord: HowNowBrownCrow#2591
Object of testing: 225
Tier of Testing: 1
Date: 06/07/2022
Testing Process: Ground power/APU gen/Engine power test on ground and in flight
Negatives: None to report
Testing Results: Works as expected. Flew around for a few mins in the default livery with no performance/page issues and the page works as expected.

**Comment by nakajimayoshi** [comment]
@tall-vish new issue found: The EXT Power animation is engaged when using the EXT switches on the runway and in the air

**Comment by rabsp9** [comment]
Quality Assurance Tester/Trainee Report

Discord          : (Ron (GETABEERINYU2)#5596)
Object of testing: (#PR 225)
Tier of Testing  : (2)
Date             : (2/10/2022)

Testing Process: 
Added Mod to for the electrical system Display.
Tested on ground:
Tested Front and Rear Ground Power
APU start up, APU Gen On/Off
Started each engine in turn and also both at the same time Per Boeing Start Proc.
Tested Gens on and off one each engine step of the process.
Monitored Voltage and Current Display to work correctly*

Followed up with a full 3 hour flight without issues.

Negatives:       
There are no issues I found with the mode, however the power system of the base Asobo aircraft is not correct.

Testing Results: 
Passed

Conclusions: 

With an APU that has 2 200gw generators the aircraft should be able to run on the APU all day long, but reports a 2 A Draw, both sides, this eventually results in the voltage dropping to approx. 21V and the electronics shutting down.

Ground power brings the aircraft back, up and left alone will fully charge the batteries in about an hour.  
 
With Engines running that’s 4 x 250gw Generators the plane only seems to charge at 1 to 2 A. This has to be wrong, two people in First Class turn on their infotainment system and 787 runs out of power.

This behaviour is the same in the base aircraft and is an opportunity now the 787 is not encrypted? 

Well I hope.

Media:       
N/A

**Comment by nakajimayoshi** [comment]
Closing due to refactor to WASM

**Pull request closed without merging**
