### PR TITLE
feat: GENX Texture and Animations

### PR DESCRIPTION
**Pull request by TJCAviation**
# Title

GENX Cowling, Spiral and Fanblades Texture updates

# Description 

Asobos Cowling, Fan Blades and Spiral were inaccurate for the GENX Engines, me and Ryanosaurus13#7000 have fixed this with new, updated textures.

# Source material

I used this image for reference: https://www.ainonline.com/sites/ainonline.com/files/uploads/2016/04/genxenginecopy.jpg

# Testing Instructions 

Download this PR and load into the sim, the Engine cowling, Fan blades and spirals should have updated textures, and should look like the image below.
# Test Results

image

# Discord Username
Toby 0#1557 & Ryanosaurus13#7000

### CODE REVIEW

**Comment by alokm95** [comment]
Quality Assurance Tester/Trainee Report

Discord : ALOKM95#2913
Object of testing: https://github.com/Heavy-Division/B78XH/pull/282
Tier of Testing : 1
Date : 26/01/2023

Testing Process:

1. Spawned into LPFR airport
2. Checked the engines have updated textures.
3. Turned on Power and started Engine
4. The Engines now have updated animations.

Negatives:
Some liveries may have engine cowlings got wrong but overall lot of liveries have it right.

Testing Results:
Passed

Conclusions:
The textures and animations of engines working as intended.

Media:

Screenshot 2023-01-26 213301


Screenshot 2023-01-26 213210

image

**Comment by TJCAviation** [comment]
> @alokm95 are you able to provide a list of the liveries that don't work with the texture update? Do they have common files?

it'll be any livery that contains an B787_10_ENGINE_COMP.PNG.DDS file...not many do from experience. 

Looking at my liveries installed. SIA 9V-SCC contains it, Can't see any others with it installed.

What will happen if a livery does have a B787_10_ENGINE_COMP.PNG.DDS file, the cowling will just be shiny again.

Works fine with all default liveries

**Comment by alokm95** [comment]
> @alokm95 are you able to provide a list of the liveries that don't work with the texture update? Do they have common files?

It seems that SIA livery has the file. I will check other liveries and see if I can list here :)

**Comment by alokm95** [comment]
image

This file is the culprit

**Comment by ko-zone** [comment]
Livery creators can update the livery with new files, since soon livery creators will have to create compatibility with the B78XH anyways, any livery creator who touched this file can also deal with it when they create compatibility with the mod. I don't see why a Singapore livery needed the comp files to be touched anyway,

**Comment by TJCAviation** [comment]
> 



> Livery creators can update the livery with new files, since soon livery creators will have to create compatibility with the B78XH anyways, any livery creator who touched this file can also deal with it when they create compatibility with the mod. I don't see why a Singapore livery needed the comp files to be touched anyway,

Exactly this...The SIA livery has it, even though it shouldn't....so It's up to the livery dev from here.

**Comment by Ryanosaurus13** [comment]
Funny enough, the Singapore Airlines livery was my first livery for FS2020 and one of the first-ever liveries for the default 78X in sim history. Back then nobody really knew what was supposed to be included in the texture files but as updates happened I just forgot to delete that one. It will be updated someday.

**Comment by TJCAviation** [comment]
> Funny enough, the Singapore Airlines livery was my first livery for FS2020 and one of the first-ever liveries for the default 78X in sim history. Back then nobody really knew what was supposed to be included in the texture files but as updates happened I just forgot to delete that one. It will be updated someday.

Ahhh! Thought something like this may have been the issue (I knew it was an older livery)

**Pull request merged**
